import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
CONFIG_PATH = PROJECT_ROOT / "config.json"
MODEL_DIR = PROJECT_ROOT / "models"
DEFAULT_MODEL_PATH = MODEL_DIR / "face_landmarker.task"
LOG_DIR = PROJECT_ROOT / "logs"
RUNTIME_DIR = PROJECT_ROOT / "runtime"
LATEST_STATE_PATH = RUNTIME_DIR / "latest_state.json"

def load_config() -> dict:
    if not CONFIG_PATH.exists():
        return {}
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)

CONF = load_config()

MIN_FACE_DETECTION_CONFIDENCE = CONF.get("MIN_FACE_DETECTION_CONFIDENCE", 0.55)
MIN_FACE_PRESENCE_CONFIDENCE = CONF.get("MIN_FACE_PRESENCE_CONFIDENCE", 0.55)
MIN_TRACKING_CONFIDENCE = CONF.get("MIN_TRACKING_CONFIDENCE", 0.55)

EAR_CLOSED_THRESHOLD = CONF.get("EAR_CLOSED_THRESHOLD", 0.18)
EAR_RECOVERY_THRESHOLD = CONF.get("EAR_RECOVERY_THRESHOLD", 0.21)
EAR_OPEN_REFERENCE = CONF.get("EAR_OPEN_REFERENCE", 0.30)
DROWSY_EYES_CLOSED_SECONDS = CONF.get("DROWSY_EYES_CLOSED_SECONDS", 2.0)

MAR_YAWN_THRESHOLD = CONF.get("MAR_YAWN_THRESHOLD", 0.38)
MAR_RECOVERY_THRESHOLD = CONF.get("MAR_RECOVERY_THRESHOLD", 0.30)
MAR_WIDE_OPEN_REFERENCE = CONF.get("MAR_WIDE_OPEN_REFERENCE", 0.55)
YAWN_SECONDS = CONF.get("YAWN_SECONDS", 1.2)

HEAD_YAW_LIMIT_DEG = CONF.get("HEAD_YAW_LIMIT_DEG", 22.0)
HEAD_PITCH_LIMIT_DEG = CONF.get("HEAD_PITCH_LIMIT_DEG", 18.0)
HEAD_ROLL_LIMIT_DEG = CONF.get("HEAD_ROLL_LIMIT_DEG", 20.0)
LOOK_AWAY_SECONDS = CONF.get("LOOK_AWAY_SECONDS", 1.0)

GAZE_HORIZONTAL_LIMIT = CONF.get("GAZE_HORIZONTAL_LIMIT", 0.18)
GAZE_VERTICAL_LIMIT = CONF.get("GAZE_VERTICAL_LIMIT", 0.16)

ATTENTION_WEIGHTS = CONF.get("ATTENTION_WEIGHTS", {
    "eyes": 0.32,
    "mouth": 0.10,
    "head": 0.20,
    "gaze": 0.22,
    "engagement": 0.16,
})

ATTENTIVE_THRESHOLD = CONF.get("ATTENTIVE_THRESHOLD", 75.0)
MODERATE_THRESHOLD = CONF.get("MODERATE_THRESHOLD", 55.0)
LOW_ATTENTION_ALERT_THRESHOLD = CONF.get("LOW_ATTENTION_ALERT_THRESHOLD", 45.0)
ALERT_COOLDOWN_SECONDS = CONF.get("ALERT_COOLDOWN_SECONDS", 3.0)

STATE_WRITE_INTERVAL_SECONDS = CONF.get("STATE_WRITE_INTERVAL_SECONDS", 0.25)
DEFAULT_LOG_INTERVAL_SECONDS = CONF.get("DEFAULT_LOG_INTERVAL_SECONDS", 0.50)

GREEN = (60, 200, 90)
YELLOW = (0, 210, 255)
RED = (40, 40, 230)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
